CREATE TABLE `agent_registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`agentName` varchar(128) NOT NULL,
	`agentVersion` varchar(32) NOT NULL DEFAULT '1.0.0',
	`description` text,
	`endpointUrl` varchar(512),
	`skills` text,
	`tasks` text,
	`capabilities` text,
	`agentCardId` varchar(128) NOT NULL,
	`signature` varchar(256),
	`signedAt` timestamp,
	`zeroclickLinked` boolean NOT NULL DEFAULT false,
	`zeroclickAgentId` varchar(128),
	`isPublished` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`manifestJson` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agent_registrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `agent_registrations_agentCardId_unique` UNIQUE(`agentCardId`)
);
--> statement-breakpoint
CREATE TABLE `promoted_context_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`cardId` int NOT NULL,
	`cardEnhancementId` int,
	`agentServiceId` int NOT NULL,
	`userId` int NOT NULL,
	`intentSummary` text,
	`intentKeywords` text,
	`offerId` varchar(128),
	`offerTitle` varchar(256),
	`offerBrand` varchar(128),
	`promotedContext` text,
	`injectedIntoReasoning` boolean NOT NULL DEFAULT false,
	`injectionPosition` enum('system_prompt','user_context','tool_result') DEFAULT 'system_prompt',
	`estimatedEarnings` decimal(10,6) DEFAULT '0.000000',
	`earningsCurrency` varchar(16) DEFAULT 'USD',
	`zeroclickRequestId` varchar(128),
	`responseTimeMs` int,
	`success` boolean NOT NULL DEFAULT true,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `promoted_context_log_id` PRIMARY KEY(`id`)
);
